### ISSUE TITLE
Cannot handle returning to previously visited grid locations

### ISSUE THREAD

**Issue by Clarvel** [bgrins/javascript-astar#43]
Trying to return to a previously visited graph location results in an error.
http://youtu.be/_LpMhxi6puY

**Comment by bibodha** [comment]
+1

**Comment by AdmiralPotato** [comment]
+1

**Comment by bgrins** [comment]
This should be fixed by https://github.com/bgrins/javascript-astar/commit/0d768b0ac51ff52c428f52ea8306969a72fe7c90, thanks @noiron
