### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by gianmarcotoso** [bgrins/javascript-astar#48]
You should definitely publish this to the npm registry.

Thanks for this, awesome work!

**Comment by DavidBadura** [comment]
:+1:

**Comment by gianmarcotoso** [comment]
Did you manage to publish it? I see that javascript-astar is still available as a package name!

**Comment by bgrins** [comment]
Pushed the current version to npm: https://www.npmjs.com/package/javascript-astar.  @gianmarcotoso can you confirm that it works for you when pulling it down?
