### ISSUE TITLE
New Graph is switching x and y values of my array items

### ISSUE THREAD

**Issue by TameAim** [bgrins/javascript-astar#65]
I have an array which represents 49 rows of 91 columns, i.e: 
0, 1, 2 .... 90
91, 92, 93 ...181
etc.
I've used a for loop to create temporary rows of 91 called **rowArray** and then pushed them into an array representing all 4459 cells called **wholeArray**. If I console.log whole array is looks to be in the same format as the astar demo requires:
0: (91) [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0]
1: (91) [1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ...etc.
i.e the first array within the array represents the first row of my game grid.

However when I pass this array into new Graph and console.log the graph, I see that astar has switched the x and y values for some reason. Notice above that the first row of the inner array representing x locations (1, 1, 0, 1, 1, 1...) is now represented by an increasing y value (1, 1, 0, 1, 1, 1...). Can anyone suggest a fix for this please?

0: Array(91)
0: GridNode {x: 0, y: 0, weight: 1, f: 0, g: 0, …}
1: GridNode {x: 0, y: 1, weight: 1, f: 47, g: 1, …}
2: GridNode {x: 0, y: 2, weight: 0, f: 0, g: 0, …}
3: GridNode {x: 0, y: 3, weight: 1, f: 49, g: 5, …}
4: GridNode {x: 0, y: 4, weight: 1, f: 49, g: 6, …}
5: GridNode {x: 0, y: 5, weight: 1, f: 0, g: 0, …}
6: GridNode {x: 0, y: 6, weight: 0, f: 0, g: 0, …}
...

`function pathFind(cellNumStart, cellNumEnd) {
    let wholeArray = [];
    let rowArray = [];
    let rowNumber = 0;
    for (let i = 0; i <= 4458; i++) {
        if (level1Array[i] == l11) {rowArray[rowNumber] = 1//grass
        } else if (level1Array[i] == l12 || level1Array[i] == l13) {rowArray[rowNumber] = 0//rock 3?
        } else if (level1Array[i] == l16) {rowArray[rowNumber] = 0//water 5?
        } else if (level1Array[i] == l17) {rowArray[rowNumber] = 0//deep water 0
        } else {rowArray[rowNumber] = 0//tree 0
        }
        if (rowNumber == 90) {
            wholeArray.push(rowArray);
            rowArray = [];
            rowNumber = -1;
        }
        rowNumber = rowNumber + 1;
    }
    let cellNumStartXY = convert91by49toXY(cellNumStart);
    let cellNumEndXY = convert91by49toXY(cellNumEnd);
    let x1 = cellNumStartXY[0] - 1;
    let y1 = cellNumStartXY[1] - 1;
    let x2 = cellNumEndXY[0] - 1;
    let y2 = cellNumEndXY[1] - 1;
    var graphWithWeight = new Graph(
		wholeArray
    );
    console.log(wholeArray);
    console.log(graphWithWeight);
	var startWithWeight = graphWithWeight.grid[x1][y1];
    var endWithWeight = graphWithWeight.grid[x2][y2];
    var resultWithWeight = astar.search(graphWithWeight, startWithWeight, endWithWeight, closest);
}`

Note that the only slight oddity I can see is that my first array, when console logged, doesn't show commas between each of the inner arrays like in the demo code.

**Comment by cjke** [comment]
@TameAim Did you resolve this by any chance? I hit something similar
